#version 430

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D out_tex;

struct Ellipsoid
{
	float mu[3];
	float sigma[3];
	float quaternion[4];
	float sh_dc[3];
	float sh_rest[45];

	float opacity;
	float Q;
};

layout(std430, binding = 1) buffer Ellipsoids
{
    Ellipsoid ellipsoids[];
};

void main()
{
	
	vec4 pixel_color = vec4(0.0, 1.0, 1.0, 1.0);

	ivec2 pos = ivec2(gl_GlobalInvocationID.xy);

	imageStore(out_tex, pos, pixel_color);
}